AWSTemplateFormatVersion: '2010-09-09'
Description: Create AWS CloudFormation Application Infrastructure (EC2, Security Groups)

Parameters:
  NetworkStackName:
    Description: Name of the network stack to import values from
    Type: String
    Default: network-stack
  
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  
  SSHLocation:
    Description: " The IP address range that can be used to SSH to the EC2 instances"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${NetworkStackName}-VPC-ID
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
  
  EC2InstanceUserdata:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: Ec2ImageId
      SecurityGroupIds:
      - Ref: InstanceSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet1a-ID
      InstanceType: t3.large
      Tags:
      - Key: Application
        Value: string
      - Key: Name
        Value: example-vpc-server-userdata
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum -y update
            yum -y install nginx php
            yum -y install mysql php-mysql
  
  EC2InstanceCfinit:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              - "php"
              - "httpd"
    Properties:
      ImageId: 
        Ref: Ec2ImageId
      SecurityGroupIds:
      - Ref: InstanceSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet1a-ID
      InstanceType: t3a.nano
      Tags:
      - Key: Application
        Value: string
      - Key: Name
        Value: example-vpc-server-cf-init
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            echo "start UserData"
            /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource EC2InstanceCfinit --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2InstanceCfinit --region ${AWS::Region}
            echo "finish UserData"

Outputs:
  EC2InstanceUserdataId:
    Description: EC2 Instance with UserData ID
    Value:
      Ref: EC2InstanceUserdata
  
  EC2InstanceCfinitId:
    Description: EC2 Instance with CF-Init ID
    Value:
      Ref: EC2InstanceCfinit
  
  SecurityGroupId:
    Description: Security Group ID
    Value:
      Ref: InstanceSecurityGroup