AWSTemplateFormatVersion: '2010-09-09'
Description: Create AWS CloudFormation Network Infrastructure (VPC, Subnets, IGW, Route Tables)

Parameters:
  Availabilityzone1:
    Description: " AZ-1 "
    Type: String
    MinLength: '0'
    MaxLength: '18'
    Default: 'us-east-1a'
  
  Availabilityzone2:
    Description: " AZ-2 "
    Type: String
    MinLength: '0'
    MaxLength: '18'
    Default: 'us-east-1b'
  
  VpcName:
    Description: Please input VPC name.
    Type: String
    Default: example-vpc
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''
  
  VpcCidrBlock:
    Type: String
    Description: Please input an IP range in VPC.
    Default: 10.0.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/16"
    ConstraintDescription: ''
  
  VpcSubnetNamePublic1a:
    Description: Please input the subnet name of example-vpc-public-subnet-1a.
    Type: String
    Default: example-vpc-public-subnet-1a
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''
  
  VpcSubnetCidrBlockPublic1a:
    Type: String
    Description: Please input an IP range in example-vpc-public-subnet-1a.
    Default: 10.0.3.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/24"
    ConstraintDescription: ''
  
  VpcSubnetNamePublic1c:
    Description: Please input the subnet name of example-vpc-public-subnet-1c.
    Type: String
    Default: example-vpc-public-subnet-1c
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''
  
  VpcSubnetCidrBlockPublic1c:
    Type: String
    Description: Please input an IP range in example-vpc-public-subnet-1c.
    Default: 10.0.4.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/24"
    ConstraintDescription: ''
  
  VpcSubnetNamePrivate1a:
    Description: Please input the subnet name of example-vpc-private-subnet-1a.
    Type: String
    Default: example-vpc-private-subnet-1a
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''
  
  VpcSubnetCidrBlockPrivate1a:
    Type: String
    Description: Please input an IP range in example-vpc-private-subnet-1a.
    Default: 10.0.1.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/24"
    ConstraintDescription: ''
  
  VpcSubnetNamePrivate1c:
    Description: Please input the subnet name of private-subnet-1c.
    Type: String
    Default: example-vpc-private-subnet-1c
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''
  
  VpcSubnetCidrBlockPrivate1c:
    Type: String
    Description: Please input an IP range in example-vpc-private-subnet-1c.
    Default: 10.0.2.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/24"
    ConstraintDescription: ''
  
  InternetGatewayName:
    Description: Please input the name of Internet Gateway.
    Type: String
    Default: example-vpc-igw
    AllowedPattern: "[-a-zA-Z0-9]*"
    ConstraintDescription: ''

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value:
          Ref: VpcName
  
  SubnetPublic1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Ref: Availabilityzone1
      CidrBlock:
        Ref: VpcSubnetCidrBlockPublic1a
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value:
          Ref: VpcSubnetNamePublic1a
  
  SubnetPublic1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Ref: Availabilityzone2
      CidrBlock:
        Ref: VpcSubnetCidrBlockPublic1c
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value:
          Ref: VpcSubnetNamePublic1c
  
  SubnetPrivate1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Ref: Availabilityzone1
      CidrBlock:
        Ref: VpcSubnetCidrBlockPrivate1a
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value:
          Ref: VpcSubnetNamePrivate1a
  
  SubnetPrivate1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Ref: Availabilityzone2
      CidrBlock:
        Ref: VpcSubnetCidrBlockPrivate1c
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value:
          Ref: VpcSubnetNamePrivate1c
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value:
          Ref: InternetGatewayName
  
  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId
      - Key: Network
        Value: Public
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  
  PublicSubnetRouteTableAssociatio1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubnetPublic1a
      RouteTableId:
        Ref: PublicRouteTable
  
  PublicSubnetRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubnetPublic1c
      RouteTableId:
        Ref: PublicRouteTable
  
  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VPC

Outputs:
  VPCId:
    Description: VPC ID
    Value:
      Ref: VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC-ID
  
  PublicSubnet1aId:
    Description: Public Subnet 1a ID
    Value:
      Ref: SubnetPublic1a
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1a-ID
  
  PublicSubnet1cId:
    Description: Public Subnet 1c ID
    Value:
      Ref: SubnetPublic1c
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1c-ID
  
  PrivateSubnet1aId:
    Description: Private Subnet 1a ID
    Value:
      Ref: SubnetPrivate1a
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1a-ID
  
  PrivateSubnet1cId:
    Description: Private Subnet 1c ID
    Value:
      Ref: SubnetPrivate1c
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1c-ID